blank_issues_enabled: false
contact_links:
    - name: Feature Request
      url: https://github.com/RooVetGit/Roo-Code/discussions/categories/feature-requests
      about: Share and vote on feature requests for Roo Code
    